RDKB-20330: PHP upgrade to 7.2.14
Reason for change: CVE fixes from 7.2.8 to 7.2.14
Test Procedure: PHP components should work fine (webui)
Risks:Medium

Change-Id: Idd8bc6dca6f68beb1d41738c6226059088aaae11
Signed-off-by: bnaray513 <Bharath_Narayanasamy@comcast.com>
(cherry picked from commit 8405af7d352a5e34e544e179153327847c2751f6)

RDKB-15487: Upgrade PHP to V7.x to address security vulnerablities

Reason for change: to resolve CVE found in earlier versions
Test Procedure:
1) Ensure that box is running php7
2) Ensure proper functioning of WebUI
Risks: Medium

Change-Id: I2b1a7d3137219e88341f580a3a7be5792ceb76f1
Signed-off-by: Sohit Singh <Sohit_Singh@comcast.com>
(cherry picked from commit ca355a92d62bc1edefcb217315c3d036aa7fe6ca)

RDKALL-974: PHP upgrade to 7.2.8

Reason for change: CVE fixes
Test Procedure: PHP components should work fine (webui)
Risks:Medium

Change-Id: 788a89369a70c1e2a4fc7dd5c99c01de45654ca4
Signed-off-by: Vineet Seth <Vineet_Seth@comcast.com>
(cherry picked from commit 3b125c5e46d8be99cb43ba8fa432436530176b93)

Manual Pick : till 7.2.7 version
---------------------------------------

commit 188097b4e9f458b3c2268ba10ac28d0938b4fd2e
Author: changqing.li@windriver.com <changqing.li@windriver.com>
Date:   Fri Jun 29 14:22:13 2018 +0800

    php: upgrade 7.2.4 -> 7.2.7

    Signed-off-by: Changqing Li <changqing.li@windriver.com>
    Signed-off-by: Khem Raj <raj.khem@gmail.com>
Change-Id: Ib56fc26fefff498b10236ea6486a5d5624f726cc
(cherry picked from commit 188097b4e9f458b3c2268ba10ac28d0938b4fd2e)

commit 75a84a920a0770b8a0e6a7925433eb7830f97187
Author: Hongxu Jia <hongxu.jia@windriver.com>
Date:   Sun Apr 15 22:28:48 2018 -0400
    php 7.2.4: fix do_compile failure on qemumips

    It caused by a new variable is declared after the label

    There is a build failure on mips:
    ...
    |sljitNativeMIPS_common.c: In function 'sljit_has_cpu_feature':
    |sljitNativeMIPS_common.c:506:3: error: a label can only be part
    of a statement and a declaration is not a statement
    |   sljit_sw fir;
    |   ^~~~~~~~
    ...

    Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
    Signed-off-by: Armin Kuster <akuster808@gmail.com>
Change-Id: I2fb36a2dc9cdb1bec78655146838b192aabcff5b
(cherry picked form commit 75a84a920a0770b8a0e6a7925433eb7830f97187)
(cherry picked from commit 6a2b3844a80dbad51f131f7b6166a2ba937a16a8)
(cherry picked from commit d043ca3a9a2fc620a277b88bf49189a4944fd031)