RDKALL-974: PHP upgrade to 7.2.8
Reason for change: CVE fixes
Test Procedure: PHP components should work fine (webui)
Risks:Medium

Signed-off-by: Vineet Seth <Vineet_Seth@comcast.com>
(cherry picked from commit 3b125c5e46d8be99cb43ba8fa432436530176b93)

Manual Pick : till 7.2.7 version
---------------------------------------

commit 188097b4e9f458b3c2268ba10ac28d0938b4fd2e
Author: changqing.li@windriver.com <changqing.li@windriver.com>
Date:   Fri Jun 29 14:22:13 2018 +0800

    php: upgrade 7.2.4 -> 7.2.7

    Signed-off-by: Changqing Li <changqing.li@windriver.com>
    Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 188097b4e9f458b3c2268ba10ac28d0938b4fd2e)

commit 75a84a920a0770b8a0e6a7925433eb7830f97187
Author: Hongxu Jia <hongxu.jia@windriver.com>
Date:   Sun Apr 15 22:28:48 2018 -0400
    php 7.2.4: fix do_compile failure on qemumips

    It caused by a new variable is declared after the label

    There is a build failure on mips:
    ...
    |sljitNativeMIPS_common.c: In function 'sljit_has_cpu_feature':
    |sljitNativeMIPS_common.c:506:3: error: a label can only be part
    of a statement and a declaration is not a statement
    |   sljit_sw fir;
    |   ^~~~~~~~
    ...

    Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
    Signed-off-by: Armin Kuster <akuster808@gmail.com>
(cherry picked form commit 75a84a920a0770b8a0e6a7925433eb7830f97187)

Change-Id: Ic1e11ba3fec2c7ce109fcca24ffd735149d85c0c