XONE-18468: Enable syslog-ng support
Reason for change: The syslog-ng can be used instead rsyslogd in yocto builds for remote logging since rsyslogd comes under GPL3 license
syslog-ng: move back from nonworking
syslog-ng: uprev to 3.5.4.1
- initscript: add status, PIDFILE and xconsole
- syslog-ng.conf: dump the version
- Fix some memory leak problems we found
- Some backport patches
- scl: fix wrong ownership issue
- libnet: add libnet enable option and add it in PACKAGECONFIG
- add HOMEPAGE
- remove INC_PR
- change some config into PACKAGECONFIG
- add PACKAGE syslog-ng-libs to fix QA issue
- use volatiles
- inherit update-rc.d and update-alternative
syslog-ng: Various fixes
* Add PACKAGECONFIG for floating json dependency
* Add PACKAGECONFIG for floating tcp-wrappers dependency
* Disable mongodb host infection problem
* Disable rabbitmq host infection problem
* Add patch for dbi host include flags issue (making dbi conditionall really work)
* Fix configure automake flags handling
syslog-ng: Improved initscript VERBOSE handling.
The messages echoed when starting and stopping syslog-ng are currently
printed regardless of the setting of VERBOSE.  Adjust the initscript so
they're only printed when VERBOSE is enabled.
syslog-ng: update configure.patch for older patch tool
The previous configure.patch can't be applied by older "patch" tool
since the line number is incorrect, for example, the "patch 2.5.4" on
CentOS 5.10.
syslog-ng: fix a multilib build failure and a QA issue
* Use BPN instead of PN to fix the multilib build failure:
ERROR: Function failed: SYSTEMD_SERVICE_lib32-syslog-ng value
lib32-syslog-ng.service does not exist
* Do not add syslog-init for systemd to fix the QA issue:
WARNING: syslog-ng: alternative target (/etc/init.d/syslog or
/etc/init.d/syslog.syslog-ng) does not exist, skipping...
WARNING: syslog-ng: NOT adding alternative provide /etc/init.d/syslog:
/etc/init.d/syslog.syslog-ng does not exist
WARNING: alt_link == alt_target: /etc/init.d/syslog ==
/etc/init.d/syslog
syslog-ng: fix do_compi1e of qemuarm while DEBUG_BUILD
The thread local storage caused arm-gcc broken while compiling
syslog-ng with option '-g -O'.
dnscache.s: Assembler messages:
dnscache.s:100: Error: invalid operands (.text and *UND* sections) for `-'
Add option --enable-thread-tls in configure to explicitly disable
thread local storage for arm while DEBUG_BUILD enabled.
syslog-ng: add gawk to RDEPENDS
This solves the following warning:
syslog-ng-3.5.4.1: syslog-ng requires /usr/bin/awk, but no providers in its
RDEPENDS [file-rdeps]
syslog-ng: Fix memory leak when udp connection is used [ LIN7-1379 ]
When udp connection is used, there are several memory leaks happen
after run a long time.
syslog-ng: Add a PACKAGECONFIG for syslog-ng-libs
This solves the following warning:
WARNING: QA Issue: syslog-ng-libs rdepends on geoip, but it isn't a build
dependency? [build-deps]
syslog-ng: add util-linux to DEPENDS list
Add util-linux to the DEPENDS list to get rid of the following QA
warning:
syslog-ng-3.5.4.1: syslog-ng-libs rdepends on util-linux-libuuid, but it isn't a build dependency? [build-deps]
syslog-ng_3.5.4.1: modify to fix the error
1) modified "--localstatedir" from /var/run to /var/lib
2) delete "Type=notify" from syslog-ng.service.
   Otherwise syslog-ng.service can't be start successfully.
syslog-ng: add UPDATE_ALTERNATIVE for syslog-service
Use ALTERNATIVE mechanism in OE to manage the syslog service to
avoid conflicts with other syslog implementations like rsyslog
or busybox.
syslog-ng: 3.5.4.1 -> 3.6.4
Upgrade syslog-ng from 3.5.4.1 to 3.6.4.
1) Modify the syslog-ng.service-the-syslog-ng-service.patch,since the datas has been changed.
2) Delete these patches,since they are not needed any more.
    afsql-afsql_dd_insert_db-refactor.patch
    deinit-the-new-config-when-reverting-to-the.patch
    free-global-LogTemplateOptions.patch
    still-free-the-unconsumed-item.patch
    syslog-ng-verify-the-list-before-del.patch
    rewrite-expr-grammar.ym-Free-up-token.patch
    logwriter-dont-allocate-a-new-buffer.patch
3) Fix WARNING:
    QA Issue: syslog-ng-libs rdepends on libpcre, but it isn't a build dependency? [build-deps]
    QA Issue: syslog-ng rdepends on libpcre, but it isn't a build dependency? [build-deps]
4) Fix ERROR: QA Issue: non -staticdev package contains static .a library:
    work/i586-poky-linux/syslog-ng/3.6.4-r0/packages-split/syslog-ng/usr/lib/syslog-ng/libtest/libsyslog-ng-test.a' [staticdev]
syslog-ng.inc: fix prerm script & class includes
The order of class includes is very important because it's the order in
which classes are evaluated. Both update-rc.d and update-alternatives
write to the prerm script, so the class order decides the script code
ordering. As they are now, prerm is:
 #!/bin/sh
        update-alternatives --remove  syslog-init /etc/init.d/syslog.syslog-ng
if [ -z "$D" ]; then
        /etc/init.d/syslog stop
fi
This causes errors because when syslog-ng is the only alternative it is
removed and then the script tries to stop it (No such file or directory)
but even if there are other alternatives, the script tries to stop
something other than syslog-ng which was removed.
By reversing the include order, prerm gets generated correctly and it
tries to stop syslog-ng before removing it:
if [ -z "$D" ]; then
        /etc/init.d/syslog stop
fi
update-alternatives --remove  syslog-init /etc/init.d/syslog.syslog-ng
syslog-ng: expand service file @variables@ earlier
Move variable expansion of @SBINDIR@, @LOCALSTATEDIR@, and @BASEBINDIR@
earlier during install, to before the systemd service file is installed
by an automake rule.
Test Procedure:built pace xg1v1 intel  image and tested syslog-ng command.
Risks: none

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit b8a40ca5d4cdd457eb3fa25359e56d2e64c94b88)
(cherry picked from commit 1a6e16bcb1145df51b15c19df0d7ef655b683f5e)
(cherry picked from commit d98907203cc2653eee1db998e30d129c9c9a063a)
(cherry picked from commit e42efe2374e56f42ac5c7fefbc224828870de950)
(cherry picked from commit 80310a34807fd952135c11d15fa245b4d39c0e02)
(cherry picked from commit 4d3f0e3f13213d07dcad35e6bdae552d70d95638)
(cherry picked from commit c0ce7599526c4dce6d889fc4a5aa007f445e6d76)
(cherry picked from commit 4e72df8d7440e9cbbb6d1d6f938beabb796db8a4)
(cherry picked from commit 26f11117088d46a56494c348736fd73b7869c59d)
(cherry picked from commit 029dffeb94cc3b6c90229189df035d15179a91e8)
(cherry picked from commit 9c449ee15bf7d87b68869b0cc09f648927c4eea1)
(cherry picked from commit 327186e4c9c9b54497c24a5da32ed5978cb66477)
(cherry picked from commit 6de2fb38b00bd4f3d45f2258003735c33e53f93a)
(cherry picked from commit 72210ea4769d9f58477931d78c4e506ef6ad776b)
(cherry picked from commit 03071511d5e2a50e7bd6507a57d876b97a81bb4d)
(cherry picked from commit 4594d24bc082d326993e7fd545ca4ac722749953)

Change-Id: I8fac0eaa3657259333f2fd1e58a445f61534ec5e